# Generated by Django 6.1.1 on 2026-09-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='Slug')),
                ('pub_type', models.CharField(choices=[('ITEM', 'ВЕЩЬ'), ('PEOPLE', 'ЛЮДИ'), ('GUIDE', 'ГИД'), ('EVENT', 'СОБЫТИЕ')], default='ITEM', max_length=10, verbose_name='Тип публикации')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('preview_image', models.ImageField(upload_to='journal/previews/', verbose_name='Превью (карточка)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='journal/heroes/', verbose_name='Главное фото статьи')),
                ('preview_text', models.TextField(blank=True, verbose_name='Краткий текст/анонс')),
                ('content', models.TextField(blank=True, verbose_name='Полный текст/контент')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации (Журнал)',
                'ordering': ['-published_at', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PublicationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('note', models.CharField(blank=True, help_text='Например: "С этим носят"', max_length=255, verbose_name='Примечание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_products', to='catalog.product')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_products', to='journal.publication')),
            ],
            options={
                'verbose_name': 'Товар в публикации',
                'verbose_name_plural': 'Товары в публикациях',
                'ordering': ['order'],
                'unique_together': {('publication', 'product')},
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='publications', through='journal.PublicationProduct', to='catalog.product', verbose_name='Связанные товары'),
        ),
    ]
