# Generated by Django 6.1.1 on 2026-09-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Год')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок этапа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/history/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'История бренда (год)',
                'verbose_name_plural': 'История бренда',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='BrandPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Порядковый номер')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='about/principles/', verbose_name='Иконка/Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Принцип бренда',
                'verbose_name_plural': 'Принципы бренда',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MainPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slogan', models.CharField(default='ОДЕЖДА КАК ЛИЧНОЕ ПРОСТРАНСТВО', max_length=255, verbose_name='Главный слоган')),
                ('manifesto', models.TextField(blank=True, help_text='Текст "KISA создаёт вещи для повседневной жизни..."', verbose_name='Текст манифеста')),
                ('team_photo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фото команды/студии')),
                ('hero_video', models.FileField(blank=True, null=True, upload_to='about/video/', verbose_name='Видео на главной (опционально)')),
            ],
            options={
                'verbose_name': 'Настройки главной страницы',
                'verbose_name_plural': 'Настройки главной страницы',
            },
        ),
        migrations.CreateModel(
            name='TeamBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('text', models.TextField(blank=True, help_text='"KISA — маленькая команда с полным вниманием к каждой вещи..."', verbose_name='Текст блока "Команда"')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/team/', verbose_name='Фото команды')),
            ],
            options={
                'verbose_name': 'Блок "Команда"',
                'verbose_name_plural': 'Блок "Команда"',
            },
        ),
    ]
