# Generated by Django 6.1.1 on 2026-09-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('telegram_url', models.URLField(blank=True, help_text='Например: https://t.me/kisa_shop или @kisa_shop', max_length=255, verbose_name='Telegram (ссылка/юзернейм)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('work_hours', models.CharField(blank=True, max_length=100, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('page_type', models.CharField(choices=[('payment_return', 'Оплата и возврат'), ('documents', 'Документы'), ('privacy', 'Политика конфиденциальности'), ('terms', 'Условия использования')], max_length=20, unique=True, verbose_name='Тип страницы')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Контент (HTML/Markdown)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Информационная страница',
                'verbose_name_plural': 'Информационные страницы',
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('email', models.EmailField(default='work@kisa', max_length=254, verbose_name='Email для сотрудничества')),
                ('description', models.TextField(blank=True, help_text='Текст для страницы/блока сотрудничества', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сотрудничество',
                'verbose_name_plural': 'Сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('telegram_url', models.URLField(blank=True, help_text='Например: https://t.me/kisa_support или @kisa_support', max_length=255, verbose_name='Telegram поддержки')),
                ('email', models.EmailField(default='support@kisa', max_length=254, verbose_name='Email поддержки')),
                ('description', models.TextField(blank=True, help_text='Текст для страницы/блока поддержки', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Поддержка',
                'verbose_name_plural': 'Поддержка',
            },
        ),
    ]
