# Generated by Django 6.1.1 on 2026-09-30 09:35

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('primary_color', colorfield.fields.ColorField(default='#000000', help_text='Цвет для текста, кнопок, ссылок и акцентов', image_field=None, max_length=25, samples=None, verbose_name='Основной цвет сайта')),
                ('secondary_color', colorfield.fields.ColorField(default='#ffffff', help_text='Фон, второстепенные элементы', image_field=None, max_length=25, samples=None, verbose_name='Вторичный цвет')),
                ('accent_color', colorfield.fields.ColorField(default='#000000', help_text='Ховеры, активные состояния', image_field=None, max_length=25, samples=None, verbose_name='Акцентный цвет')),
            ],
            options={
                'verbose_name': 'Настройки цветов сайта',
                'verbose_name_plural': 'Настройки цветов сайта',
            },
        ),
    ]
